2012-11-10 11:39:26.934 [error] <0.322.0> gen_server <0.322.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 11:39:27.060 [error] <0.322.0> CRASH REPORT Process <0.322.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 11:39:27.199 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.322.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 11:39:34.389 [error] <0.315.0> gen_server <0.315.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 11:39:34.440 [error] <0.315.0> CRASH REPORT Process <0.315.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 11:39:34.524 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.315.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 11:40:00.143 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 11:40:18.089 [error] <0.311.0> gen_server <0.311.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 11:40:18.119 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 11:40:18.136 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.311.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 11:43:03.850 [error] <0.322.0> gen_server <0.322.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 11:43:03.934 [error] <0.322.0> CRASH REPORT Process <0.322.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 11:43:04.012 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.322.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 11:43:39.050 [error] <0.329.0> gen_server <0.329.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 11:43:39.131 [error] <0.329.0> CRASH REPORT Process <0.329.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 11:43:39.202 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.329.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 11:44:54.047 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 11:45:47.744 [error] <0.315.0> gen_server <0.315.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 11:45:47.809 [error] <0.315.0> CRASH REPORT Process <0.315.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 11:45:47.904 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.315.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 12:49:52.729 [error] <0.317.0> CRASH REPORT Process <0.317.0> with 0 neighbours exited with reason: no function clause matching ct_player:init([]) line 67 in gen_server:init_it/6 line 328
2012-11-10 12:49:52.838 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.317.0> exit with reason no function clause matching ct_player:init([]) line 67 in context child_terminated
2012-11-10 12:50:10.390 [error] <0.321.0> CRASH REPORT Process <0.321.0> with 0 neighbours exited with reason: no function clause matching ct_player:init([]) line 67 in gen_server:init_it/6 line 328
2012-11-10 12:50:10.453 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.321.0> exit with reason no function clause matching ct_player:init([]) line 67 in context child_terminated
2012-11-10 12:50:51.909 [error] <0.326.0> CRASH REPORT Process <0.326.0> with 0 neighbours exited with reason: no function clause matching ct_player:init([]) line 67 in gen_server:init_it/6 line 328
2012-11-10 12:50:51.962 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.326.0> exit with reason no function clause matching ct_player:init([]) line 67 in context child_terminated
2012-11-10 12:54:53.050 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 12:55:30.390 [error] <0.312.0>@ct_client_command:execute:29 ct_client_command: error {badmatch,{error,{function_clause,[{ct_player,init,[[]],[{file,"src/ct_player.erl"},{line,67}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}}} [{ct_player_sup,start_player,1,[{file,"src/ct_player_sup.erl"},{line,21}]},{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,75}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,14}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]}].
2012-11-10 12:55:30.462 [error] <0.317.0> CRASH REPORT Process <0.317.0> with 0 neighbours exited with reason: no function clause matching ct_player:init([]) line 67 in gen_server:init_it/6 line 328
2012-11-10 12:55:30.552 [error] <0.312.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[{badmatch,{error,{function_clause,[{ct_player,init,[[]],[{file,"src/ct_player.erl"},{line,67}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}}}],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 12:55:30.619 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.317.0> exit with reason no function clause matching ct_player:init([]) line 67 in context child_terminated
2012-11-10 12:56:01.193 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 12:56:05.980 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 12:58:33.732 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 13:03:13.591 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 13:03:58.873 [error] <0.313.0> gen_server <0.313.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 13:03:58.903 [error] <0.313.0> CRASH REPORT Process <0.313.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 13:03:58.920 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.313.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 13:08:48.713 [error] <0.342.0> gen_server <0.342.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 13:08:48.821 [error] <0.342.0> CRASH REPORT Process <0.342.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 13:08:48.977 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.342.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 13:21:38.110 [error] <0.356.0> gen_server <0.356.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 13:21:38.166 [error] <0.356.0> CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 13:21:38.283 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.356.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 13:52:53.047 [error] <0.389.0> gen_server <0.389.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 13:52:53.112 [error] <0.389.0> CRASH REPORT Process <0.389.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 13:52:53.175 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.389.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 13:53:04.267 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 14:02:09.143 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 14:02:30.889 [error] <0.318.0> gen_server <0.318.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 14:02:30.960 [error] <0.318.0> CRASH REPORT Process <0.318.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 14:02:31.055 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.318.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 14:03:00.373 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 14:03:20.122 [error] <0.318.0> gen_server <0.318.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 14:03:20.233 [error] <0.318.0> CRASH REPORT Process <0.318.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 14:03:20.312 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.318.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 14:03:49.965 [error] <0.332.0> gen_server <0.332.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 14:03:50.063 [error] <0.332.0> CRASH REPORT Process <0.332.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 14:03:50.130 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.332.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 14:08:57.540 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 14:09:20.688 [error] <0.313.0>@ct_client_command:execute:29 ct_client_command: error function_clause [{gen_server,cast,[{player_state,1,<0.318.0>,undefined,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,undefined,undefined,[],[],#Fun<ct_player.0.78645111>,1001},{attack,{error,undefined}}],[{file,"gen_server.erl"},{line,194}]},{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,114}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,14}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]}].
2012-11-10 14:09:20.738 [error] <0.313.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[function_clause],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 14:13:17.609 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 14:13:35.301 [error] <0.318.0> gen_server <0.318.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 14:13:35.402 [error] <0.318.0> CRASH REPORT Process <0.318.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 14:13:35.516 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.318.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 14:19:50.949 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 14:20:27.644 [error] <0.335.0> gen_server <0.335.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19
2012-11-10 14:20:27.747 [error] <0.335.0> CRASH REPORT Process <0.335.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 19 in gen_server:terminate/6 line 747
2012-11-10 14:20:27.837 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.335.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 19 in context child_terminated
2012-11-10 18:23:21.955 [error] <0.328.0> gen_server <0.328.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 18:23:22.060 [error] <0.328.0> CRASH REPORT Process <0.328.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 18:23:22.154 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.328.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 18:27:41.931 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 18:29:27.679 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 18:35:51.148 [error] <0.334.0> gen_server <0.334.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 18:35:51.224 [error] <0.334.0> CRASH REPORT Process <0.334.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 18:35:51.277 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.334.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 18:38:19.756 [error] <0.367.0> gen_server <0.367.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 18:38:19.817 [error] <0.367.0> CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 18:38:19.935 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.367.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 18:39:04.451 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 18:43:10.724 [error] <0.350.0> gen_server <0.350.0> terminated with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87
2012-11-10 18:43:10.770 [error] <0.350.0> CRASH REPORT Process <0.350.0> with 0 neighbours exited with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87 in gen_server:terminate/6 line 747
2012-11-10 18:44:44.815 [error] <0.372.0> gen_server <0.372.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 18:44:44.861 [error] <0.372.0> CRASH REPORT Process <0.372.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 18:44:44.921 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.372.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 18:50:49.812 [error] <0.429.0> gen_server <0.429.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 18:50:49.858 [error] <0.429.0> CRASH REPORT Process <0.429.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 18:50:49.916 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.429.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 19:03:05.943 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:04:20.967 [error] <0.318.0>@ct_client_command:execute:31 ct_client_command: error badarg [{erlang,list_to_atom,[<<"1001">>],[]},{ct_player_sup,get_handler,1,[{file,"ct_player_sup.erl"},{line,33}]},{ct_client_command,do_command,2,[{file,"ct_client_command.erl"},{line,116}]},{ct_client_command,execute,2,[{file,"ct_client_command.erl"},{line,16}]}].
2012-11-10 19:04:21.983 [error] <0.318.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[badarg],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 19:04:52.063 [error] <0.352.0>@ct_client_command:execute:31 ct_client_command: error badarg [{erlang,list_to_atom,[<<"1001">>],[]},{ct_player_sup,get_handler,1,[{file,"ct_player_sup.erl"},{line,33}]},{ct_client_command,do_command,2,[{file,"ct_client_command.erl"},{line,116}]},{ct_client_command,execute,2,[{file,"ct_client_command.erl"},{line,16}]}].
2012-11-10 19:04:52.679 [error] <0.352.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[badarg],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 19:06:21.791 [error] <0.371.0>@ct_client_command:execute:31 ct_client_command: error badarg [{erlang,list_to_atom,[<<"1001">>],[]},{ct_player_sup,get_handler,1,[{file,"ct_player_sup.erl"},{line,33}]},{ct_client_command,do_command,2,[{file,"ct_client_command.erl"},{line,116}]},{ct_client_command,execute,2,[{file,"ct_client_command.erl"},{line,16}]}].
2012-11-10 19:06:28.087 [error] <0.371.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[badarg],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 19:06:38.999 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:07:45.520 [error] <0.313.0>@ct_client_command:execute:31 ct_client_command: error badarg [{erlang,list_to_atom,[<<"undefined">>],[]},{ct_player_sup,get_handler,1,[{file,"ct_player_sup.erl"},{line,33}]},{ct_client_command,do_command,2,[{file,"ct_client_command.erl"},{line,116}]},{ct_client_command,execute,2,[{file,"ct_client_command.erl"},{line,16}]}].
2012-11-10 19:07:45.544 [error] <0.313.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[badarg],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 19:07:51.402 [error] <0.313.0> gen_server <0.313.0> terminated with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87
2012-11-10 19:07:51.632 [error] <0.313.0> CRASH REPORT Process <0.313.0> with 0 neighbours exited with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87 in gen_server:terminate/6 line 747
2012-11-10 19:08:07.742 [error] <0.311.0> gen_server <0.311.0> terminated with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'/2 from ct_player:handle_cast/2 line 112
2012-11-10 19:08:07.821 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours exited with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,5,<0.311.0>,<0.306.0>,<<"TITO">>,33333,4,10,0,2,1,0,1,123,<0.170.0>,[{n,[5,6]},{nw,...},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"lazi">>},{"public_id",1001}]}}]}) in gen_server:terminate/6 line 747
2012-11-10 19:08:07.870 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.311.0> exit with reason call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,5,<0.311.0>,<0.306.0>,<<"TITO">>,33333,4,10,0,2,1,0,1,123,<0.170.0>,[{n,[5,6]},{nw,...},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"lazi">>},{"public_id",1001}]}}]}) in context child_terminated
2012-11-10 19:08:08.031 [error] <0.318.0> gen_server <0.318.0> terminated with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'/2 from ct_player:handle_cast/2 line 112
2012-11-10 19:08:08.160 [error] <0.318.0> CRASH REPORT Process <0.318.0> with 0 neighbours exited with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,1,<0.318.0>,<0.313.0>,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,<0.170.0>,[{n,[...]},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"lazi">>},{"public_id",1001}]}}]}) in gen_server:terminate/6 line 747
2012-11-10 19:08:08.242 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.318.0> exit with reason call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,1,<0.318.0>,<0.313.0>,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,<0.170.0>,[{n,[...]},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"lazi">>},{"public_id",1001}]}}]}) in context child_terminated
2012-11-10 19:09:22.009 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:10:58.050 [error] <0.327.0> gen_server <0.327.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 19:10:58.116 [error] <0.327.0> CRASH REPORT Process <0.327.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 19:10:58.265 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.327.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 19:12:35.770 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:12:41.357 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:13:10.135 [error] <0.320.0> gen_server <0.320.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 19:13:10.193 [error] <0.320.0> CRASH REPORT Process <0.320.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 19:13:10.244 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.320.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 19:13:20.758 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:14:08.214 [error] <0.327.0> gen_server <0.327.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 19:14:08.294 [error] <0.327.0> CRASH REPORT Process <0.327.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 19:14:08.354 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.327.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 19:15:18.640 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:16:39.127 [error] <0.327.0> gen_server <0.327.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 19:16:39.166 [error] <0.327.0> CRASH REPORT Process <0.327.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 19:16:39.225 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.327.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 19:17:11.743 [error] <0.320.0> gen_server <0.320.0> terminated with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'/2 from ct_player:handle_cast/2 line 112
2012-11-10 19:17:11.824 [error] <0.320.0> CRASH REPORT Process <0.320.0> with 0 neighbours exited with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,1,<0.320.0>,<0.315.0>,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,<0.170.0>,[{nw,...},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"TITO">>},{"public_id",1005}]}}]}) in gen_server:terminate/6 line 747
2012-11-10 19:17:11.906 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.320.0> exit with reason call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,1,<0.320.0>,<0.315.0>,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,<0.170.0>,[{nw,...},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"TITO">>},{"public_id",1005}]}}]}) in context child_terminated
2012-11-10 19:19:12.677 [error] <0.357.0> gen_server <0.357.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 19:19:12.758 [error] <0.357.0> CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 19:19:12.803 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.357.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 19:19:59.475 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:21:14.328 [error] <0.322.0>@ct_client_command:execute:31 ct_client_command: error badarg [{erlang,list_to_atom,[<<"1005">>],[]},{ct_player_sup,get_handler,1,[{file,"ct_player_sup.erl"},{line,33}]},{ct_client_command,do_command,2,[{file,"ct_client_command.erl"},{line,116}]},{ct_client_command,execute,2,[{file,"ct_client_command.erl"},{line,16}]}].
2012-11-10 19:21:14.402 [error] <0.322.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[badarg],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 19:21:28.370 [error] <0.320.0> gen_server <0.320.0> terminated with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'/2 from ct_player:handle_cast/2 line 112
2012-11-10 19:21:28.395 [error] <0.320.0> CRASH REPORT Process <0.320.0> with 0 neighbours exited with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,5,<0.320.0>,<0.315.0>,<<"TITO">>,33333,4,10,0,2,1,0,1,123,<0.172.0>,[{e,[6,5]},{ne,...},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"lazi">>},{"public_id",1001}]}}]}) in gen_server:terminate/6 line 747
2012-11-10 19:21:28.420 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.320.0> exit with reason call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,5,<0.320.0>,<0.315.0>,<<"TITO">>,33333,4,10,0,2,1,0,1,123,<0.172.0>,[{e,[6,5]},{ne,...},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"lazi">>},{"public_id",1001}]}}]}) in context child_terminated
2012-11-10 19:21:28.447 [error] <0.327.0> gen_server <0.327.0> terminated with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'/2 from ct_player:handle_cast/2 line 112
2012-11-10 19:21:28.469 [error] <0.327.0> CRASH REPORT Process <0.327.0> with 0 neighbours exited with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,1,<0.327.0>,<0.322.0>,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,<0.172.0>,[{e,[...]},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"lazi">>},{"public_id",1001}]}}]}) in gen_server:terminate/6 line 747
2012-11-10 19:21:28.494 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.327.0> exit with reason call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,1,<0.327.0>,<0.322.0>,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,<0.172.0>,[{e,[...]},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"lazi">>},{"public_id",1001}]}}]}) in context child_terminated
2012-11-10 19:22:27.578 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:24:18.812 [error] <0.327.0> gen_server <0.327.0> terminated with reason: no function clause matching ct_player:get_pid({ok,{player_state,1,<0.327.0>,undefined,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,undefined,undefined,...}}) line 21
2012-11-10 19:24:18.880 [error] <0.327.0> CRASH REPORT Process <0.327.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({ok,{player_state,1,<0.327.0>,undefined,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,undefined,undefined,...}}) line 21 in gen_server:terminate/6 line 747
2012-11-10 19:24:18.946 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.327.0> exit with reason no function clause matching ct_player:get_pid({ok,{player_state,1,<0.327.0>,undefined,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,undefined,undefined,...}}) line 21 in context child_terminated
2012-11-10 19:24:40.672 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:29:47.571 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:30:00.672 [error] <0.306.0>@ct_client_command:execute:31 ct_client_command: error {badmatch,{error,{badarg,[{erlang,atom_to_list,[1005],[]},{ct_player,init,1,[{file,"src/ct_player.erl"},{line,83}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}}} [{ct_player_sup,start_player,1,[{file,"src/ct_player_sup.erl"},{line,22}]},{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,77}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,16}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]}].
2012-11-10 19:30:00.732 [error] <0.306.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[{badmatch,{error,{badarg,[{erlang,atom_to_list,[1005],[]},{ct_player,init,1,[{file,"src/ct_player.erl"},{line,83}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}}}],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 19:30:00.770 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours exited with reason: bad argument in call to erlang:atom_to_list(1005) in ct_player:init/1 line 83 in gen_server:init_it/6 line 328
2012-11-10 19:30:00.938 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.311.0> exit with reason bad argument in call to erlang:atom_to_list(1005) in ct_player:init/1 line 83 in context child_terminated
2012-11-10 19:30:03.363 [error] <0.318.0> CRASH REPORT Process <0.318.0> with 0 neighbours exited with reason: bad argument in call to erlang:atom_to_list(1001) in ct_player:init/1 line 83 in gen_server:init_it/6 line 328
2012-11-10 19:30:03.364 [error] <0.313.0>@ct_client_command:execute:31 ct_client_command: error {badmatch,{error,{badarg,[{erlang,atom_to_list,[1001],[]},{ct_player,init,1,[{file,"src/ct_player.erl"},{line,83}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}}} [{ct_player_sup,start_player,1,[{file,"src/ct_player_sup.erl"},{line,22}]},{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,77}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,16}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]}].
2012-11-10 19:30:03.413 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.318.0> exit with reason bad argument in call to erlang:atom_to_list(1001) in ct_player:init/1 line 83 in context child_terminated
2012-11-10 19:30:03.519 [error] <0.313.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[{badmatch,{error,{badarg,[{erlang,atom_to_list,[1001],[]},{ct_player,init,1,[{file,"src/ct_player.erl"},{line,83}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}}}],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 19:30:32.304 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:35:00.152 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:36:08.804 [error] <0.311.0> gen_server <0.311.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 19:36:08.828 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 19:36:08.903 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.311.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 19:37:00.277 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:38:21.102 [error] <0.341.0> gen_server <0.341.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 19:38:21.141 [error] <0.341.0> CRASH REPORT Process <0.341.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 19:38:21.194 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.341.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 19:38:40.514 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:44:20.491 [error] <0.344.0> gen_server <0.344.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 19:44:20.563 [error] <0.344.0> CRASH REPORT Process <0.344.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 19:44:20.654 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.344.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 19:44:45.012 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:46:25.092 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:46:37.330 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:47:31.374 [error] <0.315.0>@ct_client_command:execute:31 ct_client_command: error badarg [{erlang,atom_to_list,[1005],[]},{ct_player_sup,start_player,1,[{file,"src/ct_player_sup.erl"},{line,29}]},{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,77}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,16}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]}].
2012-11-10 19:47:31.464 [error] <0.315.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[badarg],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 19:48:31.095 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 19:49:35.542 [error] <0.318.0> gen_server <0.318.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 19:49:35.588 [error] <0.318.0> CRASH REPORT Process <0.318.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 19:49:35.648 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.318.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 19:53:01.332 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 20:06:42.486 [error] <0.339.0> gen_server <0.339.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 20:06:42.528 [error] <0.339.0> CRASH REPORT Process <0.339.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 20:06:42.595 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.339.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 20:07:03.445 [error] <0.346.0> gen_server <0.346.0> terminated with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'/2 from ct_player:handle_cast/2 line 112
2012-11-10 20:07:03.568 [error] <0.346.0> CRASH REPORT Process <0.346.0> with 0 neighbours exited with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,1,<0.346.0>,<0.341.0>,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,<0.171.0>,[{e,[...]},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"TITO">>},{"public_id",1005}]}}]}) in gen_server:terminate/6 line 747
2012-11-10 20:07:03.628 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.346.0> exit with reason call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,1,<0.346.0>,<0.341.0>,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,<0.171.0>,[{e,[...]},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"TITO">>},{"public_id",1005}]}}]}) in context child_terminated
2012-11-10 20:08:37.373 [error] <0.517.0> gen_server <0.517.0> terminated with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21
2012-11-10 20:08:37.419 [error] <0.517.0> CRASH REPORT Process <0.517.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({error,undefined}) line 21 in gen_server:terminate/6 line 747
2012-11-10 20:08:37.471 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.517.0> exit with reason no function clause matching ct_player:get_pid({error,undefined}) line 21 in context child_terminated
2012-11-10 20:15:47.663 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 20:15:53.918 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 20:20:48.102 [error] <0.320.0> gen_server <0.320.0> terminated with reason: no function clause matching ct_player:get_pid({ok,{player_state,1,<0.327.0>,undefined,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,undefined,undefined,...}}) line 21
2012-11-10 20:20:48.141 [error] <0.320.0> CRASH REPORT Process <0.320.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({ok,{player_state,1,<0.327.0>,undefined,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,undefined,undefined,...}}) line 21 in gen_server:terminate/6 line 747
2012-11-10 20:20:48.204 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.320.0> exit with reason no function clause matching ct_player:get_pid({ok,{player_state,1,<0.327.0>,undefined,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,undefined,undefined,...}}) line 21 in context child_terminated
2012-11-10 20:21:02.480 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 20:21:15.702 [error] <0.318.0> gen_server <0.318.0> terminated with reason: no function clause matching ct_player:get_pid({ok,{player_state,5,<0.311.0>,undefined,<<"TITO">>,33333,4,10,0,2,1,0,1,123,undefined,undefined,...}}) line 21
2012-11-10 20:21:15.756 [error] <0.318.0> CRASH REPORT Process <0.318.0> with 0 neighbours exited with reason: no function clause matching ct_player:get_pid({ok,{player_state,5,<0.311.0>,undefined,<<"TITO">>,33333,4,10,0,2,1,0,1,123,undefined,undefined,...}}) line 21 in gen_server:terminate/6 line 747
2012-11-10 20:21:15.817 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.318.0> exit with reason no function clause matching ct_player:get_pid({ok,{player_state,5,<0.311.0>,undefined,<<"TITO">>,33333,4,10,0,2,1,0,1,123,undefined,undefined,...}}) line 21 in context child_terminated
2012-11-10 20:21:40.943 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 20:25:30.896 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 20:26:16.400 [error] <0.315.0>@ct_client_command:execute:21 Error when decoding bad_args
2012-11-10 20:26:16.466 [error] <0.315.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[<<"Error when decoding: bad_args">>],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 20:26:16.524 [error] <0.315.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error {badrecord,state} [{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,41}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 20:26:19.376 [error] <0.315.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error {badrecord,state} [{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,41}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 20:26:21.801 [error] <0.315.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error {badrecord,state} [{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,41}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-10 20:26:35.508 [error] <0.333.0> gen_server <0.333.0> terminated with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'/2 from ct_player:handle_cast/2 line 112
2012-11-10 20:26:35.571 [error] <0.333.0> CRASH REPORT Process <0.333.0> with 0 neighbours exited with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,1,<0.333.0>,<0.326.0>,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,<0.173.0>,[{n,[...]},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"TITO">>},{"public_id",1005}]}}]}) in gen_server:terminate/6 line 747
2012-11-10 20:26:35.612 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.333.0> exit with reason call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,1,<0.333.0>,<0.326.0>,<<"lazi">>,232323,2333,10,0,2,1,0,56,123098,<0.173.0>,[{n,[...]},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"TITO">>},{"public_id",1005}]}}]}) in context child_terminated
2012-11-10 20:26:35.728 [error] <0.320.0> gen_server <0.320.0> terminated with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'/2 from ct_player:handle_cast/2 line 112
2012-11-10 20:26:35.878 [error] <0.320.0> CRASH REPORT Process <0.320.0> with 0 neighbours exited with reason: call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,5,<0.320.0>,<0.315.0>,<<"TITO">>,33333,4,10,0,2,1,0,1,123,<0.173.0>,[{n,[5,6]},{ne,...},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"TITO">>},{"public_id",1005}]}}]}) in gen_server:terminate/6 line 747
2012-11-10 20:26:35.979 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.320.0> exit with reason call to undefined function ct_client_command:'-do_command/2-fun-0-'({player_state,5,<0.320.0>,<0.315.0>,<<"TITO">>,33333,4,10,0,2,1,0,1,123,<0.173.0>,[{n,[5,6]},{ne,...},...],...}, {obj,[{"type",<<"seen_by_info">>},{"body",{obj,[{"name",<<"TITO">>},{"public_id",1005}]}}]}) in context child_terminated
2012-11-10 20:30:23.890 [error] <0.315.0> gen_server <0.315.0> terminated with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87
2012-11-10 20:30:23.953 [error] <0.315.0> CRASH REPORT Process <0.315.0> with 0 neighbours exited with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87 in gen_server:terminate/6 line 747
2012-11-10 21:25:27.679 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-10 23:43:57.733 [error] <0.316.0> gen_server <0.316.0> terminated with reason: bad argument in ct_player:handle_cast/2 line 209
2012-11-10 23:43:57.933 [error] <0.316.0> CRASH REPORT Process <0.316.0> with 0 neighbours exited with reason: bad argument in ct_player:handle_cast/2 line 209 in gen_server:terminate/6 line 747
2012-11-10 23:43:57.995 [error] <0.75.0> Supervisor ct_player_sup had child ct_player started with {ct_player,start_link,undefined} at <0.316.0> exit with reason bad argument in ct_player:handle_cast/2 line 209 in context child_terminated
